metadata:
  maintainer: Tobias Sterbak (tsterbak)
  devicename: Fairphone 2
  devicecode: FP2
steps:
  unlock_bootloader:
  flash_recovery:
    - type: confirm_button 
      content: >
        Now you need to flash a custom recovery system on the phone. A recovery is a small subsystem on your phone, that manages updating, 
        adapting and repairing of the operating system.
    - type: call_button
      content: Once the device is fully booted, you need to reboot into the bootloader again by pressing 'Confirm and run' here. Then continue.
      command: adb_reboot_bootloader
    - type: call_button
      content: Flash a custom recovery (temporarily) by pressing 'Confirm and run'. Once it's done continue.
      command: fastboot_flash_recovery
    - type: confirm_button 
      content: >
        Now reboot into recovery to verify the installation. Do not reboot into the existing OS, since it will overwrite the recovery you just installed!
        With the device powered off, hold 'Volume Up + Power'. Release when boot logo appears.
  install_os:
    - type: call_button 
      content: >
        In the next steps, you finally flash the selected OS image.
        Wait until the TWRP screen appears. Then run the command.
        This step will format your phone and wipe all the data. It will also remove encryption and delete all files stored 
        in the internal storage. Then the OS image will be installed. This might take a while. At the end your phone will boot into the new OS.
      command: adb_twrp_wipe_and_install