steps:
  - title: "Unlock the bootloader"
    type: confirm_button
    content: "On the device, dial *#*#7378423#*#* (*#*#SERVICE#*#*) to launch the service menu."
  - title: "Unlock the bootloader"
    type: confirm_button
    content: "Go to service info > configuration and check rooting status – you can only continue if it says Bootloader unlock allowed: Yes."
  - title: "Unlock the bootloader"
    type: confirm_button
    content: "Connect the device to your PC via USB."
  - title: "Unlock the bootloader"
    type: call_button
    content: "Unlock the bootloader"
    command: "adb reboot bootloader"
  - title: "Unlock the bootloader"
    type: confirm_button
    content: "Follow the instructions on Sony’s official unlocking website to generate an unlock code for your bootloader. https://developer.sonymobile.com/unlockbootloader/unlock-yourboot-loader/"
  - title: "Unlock the bootloader"
    type: call_button_with_input
    content: "Use your code to unlock the bootloader of your device:"
    command: "fastboot oem unlock inputtext"
  - title: "Flash temporary recovery"
    type: confirm_button
    content: "Since the device resets completely, you will need to re-enable USB debugging to continue. Connect your device to your PC via USB."
  - title: "Flash temporary recovery"
    type: call_button
    content: "Reboot into bootloader"
    command: "adb reboot bootloader"
  - title: "Flash temporary recovery"
    type: call_button
    content: "Flash recovery image"
    command: "fastboot flash boot recovery"
  - title: "Flash LineageOS"
    type: call_button
    content: "Boot into recovery"
    command: "fastboot reboot"
  - title: "Flash LineageOS"
    type: confirm_button
    content: "Now tap 'Wipe'. Then tap 'Format Data' and continue with the formatting process. This will remove encryption and delete all files stored in the internal storage."
  - title: "Flash LineageOS"
    type: confirm_button
    content: "Return to the previous menu and tap 'Advanced Wipe', then select the 'Cache' and 'System' partitions and then 'Swipe to Wipe'."
  - title: "Flash LineageOS"
    type: confirm_button
    content: "On the device, go back and select “Advanced”, “ADB Sideload”, then swipe to begin sideload. Then confirm here"
  - title: "Flash LineageOS"
    type: call_button
    content: "Flash lineageOS image. Don't remove the USB-Cable!"
    command: "adb sideload image"
  - title: "Reboot"
    type: call_button
    content: "Reboot into OS"
    command: "adb reboot"
  - title: "Successfully finished flashing"
    type: text
    content: "Have fun with LineageOS!"