name: Manual build workflow

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: pip install -r requirements.txt
    - run: python scripts/download-tools.py
    - run: pyinstaller openandroidinstaller/openandroidinstaller.py --noconsole --noconfirm --onefile --icon "/assets/favicon.ico" --add-data "openandroidinstaller/assets:assets" --add-binary "openandroidinstaller/bin/adb:bin" --add-binary "openandroidinstaller/bin/fastboot:bin" --add-binary "openandroidinstaller/bin/heimdall:bin"
    # Optionally verify that it works (provided that it does not need user interaction)
    #- run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v3
      with:
        name: openandroidinstaller-${{ github.sha }}-${{ matrix.os }}
        path: dist/
